Added retries just in case the matrix endpoint is not ready
Otherwise the following exception would be raised:

Traceback (most recent call last):
  File "/home/circleci/raiden/raiden/network/transport/matrix/utils.py", line 678, in make_client
    client.api._send("GET", "/versions", api_path="/_matrix/client")
  File "/home/circleci/raiden/raiden/network/transport/matrix/client.py", line 168, in _send
    return super()._send(method, path, *args, **kwargs)
  File "/home/circleci/venv-3.7-LINUX/lib/python3.7/site-packages/matrix_client/api.py", line 691, in _send
    code=response.status_code, content=response.text
matrix_client.errors.MatrixRequestError: 404: 404 page not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/circleci/raiden/raiden/ui/app.py", line 100, in _setup_matrix
    config=config["transport"], environment=config["environment_type"]
  File "/home/circleci/raiden/raiden/network/transport/matrix/transport.py", line 311, in __init__
    environment=environment,
  File "/home/circleci/raiden/raiden/network/transport/matrix/utils.py", line 693, in make_client
    ) from last_ex
raiden.exceptions.TransportError: Unable to find a reachable Matrix server. Please check your network connectivity.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/circleci/raiden/raiden/ui/cli.py", line 887, in smoketest
    token=token,
  File "/home/circleci/raiden/raiden/tests/utils/smoketest.py", line 379, in run_smoketest
    app = run_app(**args)
  File "/home/circleci/raiden/raiden/ui/app.py", line 308, in run_app
    matrix_transport = _setup_matrix(config, routing_mode)
  File "/home/circleci/raiden/raiden/ui/app.py", line 104, in _setup_matrix
    sys.exit(1)
SystemExit: 1